apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: demo-gha
spec:
  replicas: 3
  selector:
    matchLabels:
      name: demo-gha
  template:
    metadata:
      labels:
        name: demo-gha
    spec:
      containers:
      - name: demo-gha
        image: jolopez67/demo-gha
        ports:
        - containerPort: 80
          name: http
